In [1]:
import pandas as pd
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup
import numpy as np

In [2]:
url = "https://www.basketball-reference.com/leagues/NBA_2023_per_game.html"

In [3]:
html = urlopen(url)
soup = BeautifulSoup(html)

## DataFrame

In [4]:
#colunas: tags tr
#linhas: tags td
rows = soup.findAll('tr')[1:]
players_stats = [[td.getText() for td in rows[i].findAll('td')] for i in range(len(rows))]

In [5]:
headers = [th.getText() for th in soup.findAll('tr', limit=2)[0].findAll('th')]
headers

['Rk',
 'Player',
 'Pos',
 'Age',
 'Tm',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

In [6]:
df_stats = pd.DataFrame(players_stats, columns = headers[1:])

In [7]:
df_stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Precious Achiuwa,C,23,TOR,12,0,20.4,3.0,7.7,.391,...,.848,2.0,5.0,7.0,1.3,0.2,0.6,1.3,1.6,8.8
1,Steven Adams,C,29,MEM,31,31,26.5,3.5,6.0,.591,...,.325,4.9,5.6,10.5,2.2,0.8,1.1,1.9,2.3,7.9
2,Bam Adebayo,C,25,MIA,32,32,35.1,8.3,15.5,.532,...,.833,2.6,7.2,9.8,3.2,1.0,0.7,3.1,3.2,20.9
3,Ochai Agbaji,SG,22,UTA,16,0,7.9,1.1,2.6,.405,...,.444,0.4,0.7,1.1,0.2,0.1,0.0,0.0,0.8,2.7
4,Santi Aldama,PF,22,MEM,33,16,23.3,3.4,7.2,.475,...,.716,1.2,4.0,5.2,1.3,0.7,0.9,0.6,2.3,9.6

In [8]:
df_stats.tail()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
512,Delon Wright,PG,30,WAS,8,0,19.5,1.8,4.6,.378,...,.727,0.6,1.4,2.0,3.8,2.3,0.5,0.8,1.1,5.1
513,McKinley Wright IV,PG,24,DAL,6,0,10.0,0.8,1.8,.455,...,.000,0.7,0.8,1.5,1.5,0.8,0.2,0.8,1.3,1.7
514,Thaddeus Young,PF,34,TOR,32,9,17.4,2.3,4.2,.545,...,.737,1.7,2.0,3.7,1.7,1.1,0.1,0.8,1.9,5.1
515,Trae Young,PG,24,ATL,32,32,35.6,8.7,21.0,.415,...,.892,0.8,2.1,2.8,9.9,0.8,0.2,3.8,1.5,27.4
516,Ivica Zubac,C,25,LAC,35,35,29.9,4.0,6.5,.624,...,.675,3.5,7.5,11.0,1.1,0.4,1.5,2.1,3.1,10.3

In [9]:
df_stats.shape

(517, 29)

## Cleaning

In [10]:
df_stats.isnull().sum()

Player    24
Pos       24
Age       24
Tm        24
G         24
GS        24
MP        24
FG        24
FGA       24
FG%       24
3P        24
3PA       24
3P%       24
2P        24
2PA       24
2P%       24
eFG%      24
FT        24
FTA       24
FT%       24
ORB       24
DRB       24
TRB       24
AST       24
STL       24
BLK       24
TOV       24
PF        24
PTS       24
dtype: int64

In [11]:
df_stats = df_stats.dropna()
df_stats.isnull().sum()

Player    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
dtype: int64

In [12]:
df_stats.dtypes

Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [13]:
strings = ['Player','Pos','Tm']
        
df_stats = df_stats.apply(pd.to_numeric, errors='ignore')

for df in df_stats:
    if df in [i for i in strings]:
        df_stats[df] = df_stats[df].astype('string')

df_stats.dtypes

Player     string
Pos        string
Age         int64
Tm         string
G           int64
GS          int64
MP        float64
FG        float64
FGA       float64
FG%       float64
3P        float64
3PA       float64
3P%       float64
2P        float64
2PA       float64
2P%       float64
eFG%      float64
FT        float64
FTA       float64
FT%       float64
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

# Players Stats

In [14]:
mean_games = df_stats.G.mean().round()
mean_games

23.0

In [15]:
df_stats = df_stats[df_stats.G >= mean_games]

## Top 10 Pointers for position

In [57]:
df_stats['Pos'].value_counts()

SG    78
PF    71
PG    59
C     49
SF    43
Name: Pos, dtype: Int64

In [58]:
def top_players(df,stats,show_stats=None,top=None):
    
    df = df.sort_values(by=[stats], ascending = False)
    df.index = np.arange(1,len(df) + 1)
    if show_stats == None:
        
        if top == None:
            return df.head(10)
        return df.head(top)
    
    if top == None:
        
        if show_stats == None:
            return df.head(10)
        return df[show_stats].head(10)
        
    return df[show_stats].head(top)

### Top 10 Centers

In [18]:
centers = df_stats[df_stats.Pos == 'C']

In [55]:
centers = df_stats[df_stats.Pos == 'C']
top_players(centers,'PTS')[['Player','PTS','FG%','FT%','3P','3P%']]

            Player   PTS    FG%    FT%   3P    3P%
1      Joel Embiid  33.8  0.534  0.852  1.1  0.341
2    Anthony Davis  27.4  0.594  0.826  0.4  0.290
3    Pascal Siakam  26.5  0.484  0.777  1.4  0.336
4     Nikola Jokić  25.5  0.616  0.806  0.8  0.338
5      Bam Adebayo  20.9  0.532  0.833  0.0  0.100
6    Deandre Ayton  17.7  0.609  0.731  0.2  0.389
7   Nikola Vučević  16.7  0.508  0.853  1.7  0.375
8     Myles Turner  16.1  0.543  0.760  1.6  0.409
9     Jusuf Nurkić  14.8  0.541  0.680  0.9  0.464
10     Brook Lopez  14.8  0.507  0.800  2.0  0.385

### Top 10 Guards

In [59]:
guards = df_stats[(df_stats.Pos == 'PG') | (df_stats.Pos == 'SG') ]
top_players(guards,'PTS')[['Player','PTS','eFG%','FG%','FT%','3P','3P%']]

                     Player   PTS   eFG%    FG%    FT%   3P    3P%
1               Luka Dončić  33.7  0.571  0.507  0.741  2.9  0.358
2   Shai Gilgeous-Alexander  31.4  0.529  0.505  0.920  1.0  0.351
3             Stephen Curry  30.0  0.625  0.500  0.919  5.0  0.434
4          Donovan Mitchell  28.4  0.584  0.488  0.879  3.9  0.419
5            Damian Lillard  27.8  0.549  0.439  0.906  4.2  0.373
6                Trae Young  27.4  0.468  0.415  0.892  2.2  0.310
7              Devin Booker  27.1  0.534  0.477  0.850  2.3  0.370
8                 Ja Morant  26.8  0.492  0.450  0.744  1.7  0.327
9              Kyrie Irving  26.1  0.565  0.488  0.913  3.0  0.362
10          Anthony Edwards  23.7  0.533  0.464  0.732  2.6  0.367

### Top 10 Forward

In [60]:
forward = df_stats[(df_stats.Pos == 'PF') | (df_stats.Pos == 'SF')]
top_players(forward,'PTS')[['Player','PTS','eFG%','FG%','FT%','3P','3P%']]

                   Player   PTS   eFG%    FG%    FT%   3P    3P%
1   Giannis Antetokounmpo  32.1  0.550  0.533  0.645  0.8  0.253
2            Jayson Tatum  31.0  0.550  0.473  0.858  3.3  0.354
3            Kevin Durant  29.9  0.607  0.560  0.928  1.8  0.370
4            LeBron James  28.5  0.553  0.506  0.753  2.1  0.309
5            Jaylen Brown  27.0  0.553  0.492  0.802  2.5  0.331
6           DeMar DeRozan  26.3  0.522  0.511  0.885  0.4  0.286
7         Zion Williamson  26.2  0.618  0.610  0.709  0.3  0.368
8           Julius Randle  23.8  0.545  0.470  0.759  2.6  0.347
9             Paul George  23.7  0.532  0.450  0.881  3.0  0.379
10        Lauri Markkanen  23.6  0.630  0.533  0.847  3.0  0.429

## Top 10 AST

In [62]:
top_players(df_stats,'AST')[['Player','AST','TOV','PTS','eFG%']]

               Player   AST  TOV   PTS   eFG%
1   Tyrese Haliburton  10.2  2.6  20.8  0.583
2          Trae Young   9.9  3.8  27.4  0.468
3        Nikola Jokić   9.5  3.5  25.5  0.642
4          Chris Paul   9.0  2.2  13.0  0.498
5         Luka Dončić   8.9  3.7  33.7  0.571
6           Ja Morant   8.1  3.7  26.8  0.492
7   Russell Westbrook   7.8  3.5  14.6  0.451
8      Darius Garland   7.8  3.2  21.3  0.525
9         Mike Conley   7.5  1.7   9.9  0.483
10       Jrue Holiday   7.5  3.3  18.9  0.525

## Top 10 PTS

In [80]:
top_players(df_stats,'PTS')[['Player','PTS','eFG%','FG%','FT%','3P','3P%']]

                     Player   PTS   eFG%    FG%    FT%   3P    3P%
1               Joel Embiid  33.8  0.559  0.534  0.852  1.1  0.341
2               Luka Dončić  33.7  0.571  0.507  0.741  2.9  0.358
3     Giannis Antetokounmpo  32.1  0.550  0.533  0.645  0.8  0.253
4   Shai Gilgeous-Alexander  31.4  0.529  0.505  0.920  1.0  0.351
5              Jayson Tatum  31.0  0.550  0.473  0.858  3.3  0.354
6             Stephen Curry  30.0  0.625  0.500  0.919  5.0  0.434
7              Kevin Durant  29.9  0.607  0.560  0.928  1.8  0.370
8              LeBron James  28.5  0.553  0.506  0.753  2.1  0.309
9          Donovan Mitchell  28.4  0.584  0.488  0.879  3.9  0.419
10           Damian Lillard  27.8  0.549  0.439  0.906  4.2  0.373

## Top 10 eFG%

In [86]:
top_players(df_stats,'eFG%')[['Player','PTS','eFG%','FG%','FT%','3P','3P%','G','Tm']]

               Player   PTS   eFG%    FG%    FT%   3P    3P%   G   Tm
1        Jericho Sims   3.7  0.787  0.787  0.800  0.0    NaN  28  NYK
2      DeAndre Jordan   4.7  0.760  0.753  0.472  0.0  1.000  27  DEN
3        Drew Eubanks   5.9  0.757  0.748  0.650  0.1  0.667  33  POR
4      Daniel Gafford   7.1  0.750  0.750  0.608  0.0    NaN  37  WAS
5      Walker Kessler   6.9  0.746  0.746  0.545  0.0    NaN  35  UTA
6         Nic Claxton  11.9  0.743  0.743  0.460  0.0  0.000  32  BRK
7   Mitchell Robinson   7.6  0.724  0.724  0.545  0.0    NaN  28  NYK
8       Dwight Powell   6.0  0.717  0.717  0.672  0.0  0.000  31  DAL
9          Josh Green   7.0  0.699  0.583  0.711  1.0  0.444  25  DAL
10     Charles Bassey   4.9  0.686  0.671  0.667  0.1  0.333  23  SAS

## TOP 10 3P
#### 3-Point Field Goals Per Game

In [87]:
top_players(df_stats,'3P',['Player','3P','3PA','3P%','PTS','2P','FT','G','Tm','Age','Tm'])

               Player   3P   3PA    3P%   PTS   2P   FT   G   Tm  Age   Tm
1       Stephen Curry  5.0  11.6  0.434  30.0  5.0  4.8  26  GSW   34  GSW
2      Damian Lillard  4.2  11.3  0.373  27.8  4.2  6.7  23  POR   32  POR
3    Donovan Mitchell  3.9   9.3  0.419  28.4  6.0  4.8  32  CLE   26  CLE
4     Anfernee Simons  3.9  10.2  0.382  22.4  4.1  2.6  33  POR   23  POR
5       Klay Thompson  3.8  10.0  0.379  19.1  3.1  1.6  29  GSW   32  GSW
6         Buddy Hield  3.8   8.9  0.427  17.9  2.6  1.2  36  IND   30  IND
7        Jayson Tatum  3.3   9.4  0.354  31.0  6.9  7.3  34  BOS   24  BOS
8         Tyler Herro  3.3   8.4  0.396  21.1  4.2  2.8  28  MIA   23  MIA
9       Malik Beasley  3.2   8.6  0.369  14.1  1.9  0.7  38  UTA   26  UTA
10  Tyrese Haliburton  3.1   7.6  0.411  20.8  4.3  2.8  34  IND   22  IND

## TOP 5 3P%
#### Only players over the mean of 3PA

In [88]:
mean_3pp = df_stats['3PA'].mean()
df_3pp = df_stats[df_stats['3PA'] > mean_3pp]

In [89]:
top_players(df_3pp,'3P%',['Player','3P%','3PA','3P','PTS','2P','FT','G','Tm'],5)

                     Player    3P%  3PA   3P   PTS   2P   FT   G   Tm
1                Damion Lee  0.493  3.8  1.9   8.5  0.9  1.0  37  PHO
2              Luke Kennard  0.476  4.1  2.0   8.8  1.2  0.5  25  LAC
3  Kentavious Caldwell-Pope  0.471  4.5  2.1  11.6  2.0  1.2  34  DEN
4                Alec Burks  0.452  4.6  2.1  14.0  2.2  3.3  25  DET
5                Al Horford  0.450  4.8  2.1   9.7  1.6  0.2  27  BOS

## TOP 10 2P
#### 2-Point Field Goals Per Game

In [67]:
top_players(df_stats,'2P',['Player','2P','2PA','2P%','PTS','3P','FT','G','Tm'])

                     Player    2P   2PA    2P%   PTS   3P    FT   G   Tm
1     Giannis Antetokounmpo  10.7  18.5  0.578  32.1  0.8   8.4  30  MIL
2               Joel Embiid  10.2  18.0  0.567  33.8  1.1  10.2  26  PHI
3             Anthony Davis   9.8  15.9  0.618  27.4  0.4   6.6  25  LAL
4           Zion Williamson   9.7  15.6  0.621  26.2  0.3   6.0  27  NOP
5   Shai Gilgeous-Alexander   9.5  17.9  0.530  31.4  1.0   9.3  32  OKC
6              LeBron James   9.1  15.3  0.593  28.5  2.1   4.0  28  LAL
7             DeMar DeRozan   8.9  16.9  0.530  26.3  0.4   7.3  35  CHI
8              Kevin Durant   8.9  14.2  0.624  29.9  1.8   6.8  34  BRK
9              Nikola Jokić   8.8  13.2  0.667  25.5  0.8   5.5  32  DEN
10              Luka Dončić   8.5  14.4  0.591  33.7  2.9   8.0  33  DAL

## TOP 5 2P%
#### Only players over the mean of 2PA

In [68]:
mean_2pp = df_stats['2PA'].mean()
df_2pp = df_stats[df_stats['2PA'] > mean_2pp]

In [69]:
top_players(df_2pp,'2P%',['Player','2P%','2PA','2P','PTS','3P','FT','G','Tm'],5)

           Player    2P%   2PA   2P   PTS   3P   FT   G   Tm
1     Nic Claxton  0.747   7.2  5.3  11.9  0.0  1.3  32  BRK
2    Aaron Gordon  0.677   8.4  5.7  17.3  1.0  2.9  30  DEN
3     Rudy Gobert  0.675   7.8  5.3  13.8  0.0  3.2  30  MIN
4  Brandon Clarke  0.668   6.1  4.1  10.1  0.0  1.8  34  MEM
5    Nikola Jokić  0.667  13.2  8.8  25.5  0.8  5.5  32  DEN

## TOP 5 FT
#### Free Throws Goals Per Game

In [70]:
top_players(df_stats,'FT',['Player','FT','FTA','FT%','PTS','3P','2P','G','Tm'])

                     Player    FT   FTA    FT%   PTS   3P    2P   G   Tm
1               Joel Embiid  10.2  11.9  0.852  33.8  1.1  10.2  26  PHI
2   Shai Gilgeous-Alexander   9.3  10.2  0.920  31.4  1.0   9.5  32  OKC
3     Giannis Antetokounmpo   8.4  13.0  0.645  32.1  0.8  10.7  30  MIL
4               Luka Dončić   8.0  10.8  0.741  33.7  2.9   8.5  33  DAL
5                Trae Young   7.7   8.7  0.892  27.4  2.2   6.5  32  ATL
6              Jayson Tatum   7.3   8.5  0.858  31.0  3.3   6.9  34  BOS
7             DeMar DeRozan   7.3   8.2  0.885  26.3  0.4   8.9  35  CHI
8              Kevin Durant   6.8   7.4  0.928  29.9  1.8   8.9  34  BRK
9            Damian Lillard   6.7   7.4  0.906  27.8  4.2   4.2  23  POR
10            Anthony Davis   6.6   8.0  0.826  27.4  0.4   9.8  25  LAL

## TOP 10 2P%
#### Only players over the mean of FTA

In [71]:
mean_2pp = df_stats['FTA'].mean()
df_2pp = df_stats[df_stats['FTA'] > mean_2pp]

In [72]:
top_players(df_stats,'FT%',['Player','FT%','FTA','FT','PTS','3P','2P','G','Tm'])

              Player    FT%  FTA   FT   PTS   3P   2P   G   Tm
1     Troy Brown Jr.  1.000  0.6  0.6   6.5  1.0  1.4  33  LAL
2          KZ Okpala  1.000  0.3  0.3   1.6  0.2  0.3  23  SAC
3         Seth Curry  0.944  0.8  0.7   8.3  1.5  1.5  23  BRK
4   Garrison Mathews  0.939  1.2  1.1   4.9  1.2  0.1  28  HOU
5        Patty Mills  0.933  0.6  0.6   5.8  1.3  0.8  24  BRK
6      Edmond Sumner  0.929  1.9  1.7   7.1  0.5  1.9  30  BRK
7       Luke Kennard  0.929  0.6  0.5   8.8  2.0  1.2  25  LAC
8       Kevin Durant  0.928  7.4  6.8  29.9  1.8  8.9  34  BRK
9         Damion Lee  0.925  1.1  1.0   8.5  1.9  0.9  37  PHO
10     Kendrick Nunn  0.923  0.5  0.4   5.3  0.8  1.2  28  LAL

## DEFENSIVE STATS

In [73]:
def_stats = ['Player','BLK','STL','TRB','DRB','ORB','G','Tm']

### TOP 10 BLK

In [74]:
top_players(df_stats,'BLK',def_stats)

                Player  BLK  STL   TRB  DRB  ORB   G   Tm
1          Brook Lopez  2.6  0.6   5.9  4.1  1.8  34  MIL
2          Nic Claxton  2.4  0.8   8.5  6.0  2.5  32  BRK
3         Myles Turner  2.2  0.6   8.0  6.6  1.4  30  IND
4        Anthony Davis  2.1  1.3  12.1  9.0  3.1  25  LAL
5       Walker Kessler  1.8  0.2   6.3  4.0  2.3  35  UTA
6    Mitchell Robinson  1.8  0.7   8.7  4.4  4.3  28  NYK
7              Bol Bol  1.6  0.5   7.1  5.8  1.3  37  ORL
8   Kristaps Porziņģis  1.6  1.0   9.1  7.0  2.0  33  WAS
9          Joel Embiid  1.6  1.2   9.7  7.9  1.8  26  PHI
10        Kevin Durant  1.5  0.8   6.9  6.6  0.4  34  BRK

### TOP 10 STL

In [75]:
top_players(df_stats,'STL',def_stats)

                     Player  BLK  STL  TRB  DRB  ORB   G   Tm
1                OG Anunoby  0.8  2.2  5.8  4.4  1.4  32  TOR
2              Jimmy Butler  0.3  2.1  6.7  4.7  2.0  23  MIA
3         De'Anthony Melton  0.4  2.0  4.7  3.5  1.1  31  PHI
4           Anthony Edwards  0.6  1.8  6.1  5.4  0.7  36  MIN
5           Dejounte Murray  0.4  1.7  5.4  4.7  0.7  31  ATL
6   Shai Gilgeous-Alexander  1.1  1.7  4.8  4.0  0.8  32  OKC
7               Luka Dončić  0.6  1.7  8.8  7.8  1.0  33  DAL
8         Tyrese Haliburton  0.4  1.7  3.7  3.1  0.7  34  IND
9            Gary Trent Jr.  0.2  1.6  2.1  1.7  0.4  29  TOR
10          Kelly Oubre Jr.  0.4  1.6  5.1  3.6  1.5  35  CHO

### TOP 10 TOTAL REBOUNDS PER GAME

In [76]:
top_players(df_stats,'TRB',def_stats)

                   Player  BLK  STL   TRB  DRB  ORB   G   Tm
1        Domantas Sabonis  0.5  0.8  12.3  9.4  2.9  33  SAC
2           Anthony Davis  2.1  1.3  12.1  9.0  3.1  25  LAL
3             Rudy Gobert  1.3  0.8  12.0  8.4  3.5  30  MIN
4            Clint Capela  1.3  0.6  11.9  7.6  4.3  27  ATL
5   Giannis Antetokounmpo  0.9  0.9  11.8  9.6  2.3  30  MIL
6             Ivica Zubac  1.5  0.4  11.0  7.5  3.5  35  LAC
7            Nikola Jokić  0.7  1.4  10.9  8.8  2.1  32  DEN
8            Steven Adams  1.1  0.8  10.5  5.6  4.9  31  MEM
9          Nikola Vučević  0.9  0.6  10.3  8.3  2.0  35  CHI
10          Jarrett Allen  1.2  0.8  10.2  7.2  3.0  29  CLE

### TOP 10 DEFENSIVE REBOUNDS PER GAME

In [77]:
top_players(df_stats,'DRB',def_stats)

                   Player  BLK  STL   TRB  DRB  ORB   G   Tm
1   Giannis Antetokounmpo  0.9  0.9  11.8  9.6  2.3  30  MIL
2        Domantas Sabonis  0.5  0.8  12.3  9.4  2.9  33  SAC
3           Anthony Davis  2.1  1.3  12.1  9.0  3.1  25  LAL
4            Nikola Jokić  0.7  1.4  10.9  8.8  2.1  32  DEN
5             Rudy Gobert  1.3  0.8  12.0  8.4  3.5  30  MIN
6          Nikola Vučević  0.9  0.6  10.3  8.3  2.0  35  CHI
7             Joel Embiid  1.6  1.2   9.7  7.9  1.8  26  PHI
8             Luka Dončić  0.6  1.7   8.8  7.8  1.0  33  DAL
9           Julius Randle  0.3  0.7   9.7  7.7  2.0  36  NYK
10           Clint Capela  1.3  0.6  11.9  7.6  4.3  27  ATL

### TOP 10 OFFENSIVE REBOUNDS PER GAME

In [78]:
top_players(df_stats,'ORB',def_stats,10)

               Player  BLK  STL   TRB  DRB  ORB   G   Tm
1        Steven Adams  1.1  0.8  10.5  5.6  4.9  31  MEM
2        Clint Capela  1.3  0.6  11.9  7.6  4.3  27  ATL
3   Mitchell Robinson  1.8  0.7   8.7  4.4  4.3  28  NYK
4         Rudy Gobert  1.3  0.8  12.0  8.4  3.5  30  MIN
5         Ivica Zubac  1.5  0.4  11.0  7.5  3.5  35  LAC
6         Jalen Duren  0.8  0.5   8.6  5.2  3.4  35  DET
7       Mason Plumlee  0.8  0.7   9.2  5.8  3.3  36  CHO
8      Alperen Şengün  0.9  0.7   8.7  5.4  3.3  32  HOU
9        Jakob Poeltl  1.1  0.9   9.0  5.7  3.3  27  SAS
10      Anthony Davis  2.1  1.3  12.1  9.0  3.1  25  LAL